## Практическая работа

В этой практической работе пять обязательных задач.

*Обязательные задачи* помогут проверить, что вы действительно усвоили материал модуля. Сдайте их на проверку.

Удачи!

Цели практической работы: 


1.   Потренироваться в обучении модели линейной регрессии.
2.   Потренироваться в обучении модели логистической регрессии. 
3.   Потренироваться в обучении модели многослойного персептрона.





Что оценивается:

*   Все пункты и критерии приёмки по каждому заданию выполнены.
*   Код оформлен и работает корректно.





Как отправить работу на проверку:

Сдайте практическую работу этого модуля через систему контроля версий Git сервиса Skillbox GitLab. После загрузки работы на проверку напишите об этом в личном кабинете своему куратору.

В этом задании вам нужно построить модель классификации, определяющую категорию цены/цену подержанного автомобиля в зависимости от характеристик транспортного средства. 

Мы будем использовать датасет из коллекции подержанных автомобилей, выставленных на продажу в Соединенных Штатах. Он уже подготовлен, без выбросов и с категориальными фичами, преобразованными с помощью one hot encoding, и количественными фичами, стандартизированными с помощью скейлеров.


### Описание датасета:
- `id`: идентификатор записи;
- `is_manufacturer_name`: признак производителя автомобиля;

- `region_*`: регион;
- `x0_*`: тип топлива;
- `manufacturer_*`: производитель;
- `short_model_*`: сокращённая модель автомобиля;
- `title_status_*`: статус;
- `transmission_*`: коробка передач;
- `state_*`: штат;
- `age_category_*`: возрастная категория автомобиля;

- `std_scaled_odometer`: количество пройденных миль (после стандартизации);
- `year_std`: год выпуска (после стандартизации);
- `lat_std`: широта (после стандартизации);
- `long_std`: долгота (после стандартизации);
- `odometer/price_std`: отношение стоимости к пробегу автомобиля (после стандартизации);
- `desc_len_std`: количество символов в тексте объявления о продаже (после стандартизации);
- `model_in_desc_std`: количество наименований модели автомобиля в тексте объявления о продаже (после стандартизации);
- `model_len_std`: длина наименования автомобиля (после стандартизации);
- `model_word_count_std`: количество слов в наименовании автомобиля (после стандартизации);
- `month_std`: номер месяца размещения объявления о продаже автомобиля (после стандартизации);
- `dayofweek_std`: день недели размещения объявления о продаже автомобиля (после стандартизации);
- `diff_years_std`: количество лет между годом производства автомобиля и годом размещения объявления о продаже автомобиля (после стандартизации);

- `price`: стоимость;
- `price_category`: категория цены.

## Обязательные задачи

In [7]:
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import accuracy_score, confusion_matrix, mean_absolute_error
from sklearn.model_selection import train_test_split 
from sklearn.neural_network import MLPClassifier

In [9]:
df = pd.read_csv('vehicles_dataset_prepared.csv')
df.head()

id  price price_category  is_audi  is_ford  is_chevrolet  \
0  7308295377  54990           high        0        0             0   
1  7316380095  16942         medium        0        1             0   
2  7313733749  35590           high        0        0             0   
3  7308210929  14500         medium        0        0             0   
4  7303797340  14590         medium        0        0             0   

   is_toyota  x0_diesel  x0_electric  x0_gas  ...  long_std  year_std  \
0          0        1.0          0.0     0.0  ...  0.484245  1.322394   
1          0        0.0          0.0     0.0  ...  1.110800  0.695973   
2          0        0.0          0.0     1.0  ...  0.531185  0.852578   
3          1        0.0          0.0     1.0  ...  0.853562  0.226157   
4          0        0.0          0.0     0.0  ...  0.557607  0.069552   

   odometer/price_std  desc_len_std  model_in_desc_std  model_len_std  \
0           -0.510784      0.632075          -0.155788       1.163032   
1           -0.402947     -0.646781          -0.155788       0.932087   
2           -0.514480      0.560744          -0.155788       0.470197   
3           -0.241883      0.180435          -0.155788      -0.915473   
4           -0.333074      0.766366          -0.155788       1.163032   

   model_word_count_std  month_std  dayofweek_std  diff_years_std  
0              1.910669  -0.615846       1.120284       -1.322394  
1              1.235799   1.623784      -1.374972       -0.695973  
2              0.560930  -0.615846      -0.376870       -0.852578  
3             -0.788810  -0.615846       1.120284       -0.226157  
4              1.910669  -0.615846       0.122182       -0.069552  

[5 rows x 1463 columns]

**Задача 0. Линейная регрессия**

Вспомните задачу по предсказанию стоимости поддержанного автомобиля. Попробуем обучить модель линейной регрессии для предсказания цены автомобиля (колонка `price`). Для этого проделайте следующие шаги:

- Подготовьте данные: удалите колонки, которые косвенно содержат информацию о целевой переменной (`odometer/price_std`, `price_category`).
- Разделите выборку на треин и тест в отношении 70/30.
- Обучите модель линейной регрессии с дефолтными параметрами.
- Посчитайте значение метрики mae на тестовой выборке для линейной регрессии.
- Выведите получившиеся коэффициенты линейной регрессии при каждом параметре обучающей выборки с помощью метода `coef_`. Есть ли коэффициенты, которые равны нулю? Если есть, выведите названия фичей с нулевым коэффициентом
- Удалите фичи, коэффициенты которых равны нулю. И переобучите модель. Убедитесь, что значение метрики не изменилось.



In [15]:
import numpy as np
df_prepared = df.drop(columns=['odometer/price_std', 'price_category'])

X = df_prepared.drop(columns=['price'])
y = df_prepared['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


feature_names = X_train.columns

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_pred_train = model.predict(X_train)
mae_train = mean_absolute_error(y_train, y_pred_train)
print(f"MAE на обучающей выборке: {mae_train}")

y_pred_test = model.predict(X_test)
mae_test = mean_absolute_error(y_test, y_pred_test)
print(f"MAE на тестовой выборке: {mae_test}")

coefficients = model.coef_

print('\nКоэффициенты линейной регрессии:')
for feature, coef in zip(feature_names, coefficients):
    print(f'{feature}: {coef}')


zero_coef_features = feature_names[np.isclose(coefficients, 0)]
print('\nФичи с нулевыми коэффициентами:')
print(zero_coef_features)

X_train_filtered = X_train.drop(columns=zero_coef_features)
X_test_filtered = X_test.drop(columns=zero_coef_features)

model_filtered = LinearRegression()
model_filtered.fit(X_train_filtered, y_train)

y_pred_filtered = model_filtered.predict(X_test_filtered)
mae_filtered = mean_absolute_error(y_test, y_pred_filtered)
print(f'\nMAE после удаления фичей с нулевыми коэффициентами: {mae_filtered}')
#значение метрики в этот раз не изменились, вернул 'id'

MAE на обучающей выборке: 3473.4842360694606
MAE на тестовой выборке: 4600.341119684605

Коэффициенты линейной регрессии:
id: 6.3595102883915654e-06
is_audi: 254.30385694452661
is_ford: 1073.9083955930032
is_chevrolet: -184.76392251792026
is_toyota: 471.49883620737023
x0_diesel: 5848.60657899518
x0_electric: -2828.870374491994
x0_gas: -1494.5886384370556
x0_hybrid: -780.5406949313794
x0_other: -744.608038885143
std_scaled_odometer: -3529.6567495904283
short_model_-benz: -5706.119238911191
short_model_1: -7089.73739482708
short_model_124: 0.0014211719444574555
short_model_128i: -8435.624514343437
short_model_135i: -4437.962284571656
short_model_1500: -499.6193578261081
short_model_163869: 301.88402985902985
short_model_1928: 0.0004215836420371488
short_model_1951: 11515.895244384688
short_model_1954: 2447.6970245578395
short_model_1960s: -3561.6813550231122
short_model_1966: 41204.78817125912
short_model_1968: 22801.394204019947
short_model_1972: 11668.666034635375
short_model_1977: 0.0

**Задача 1. Логистическая регрессия**

Теперь в рамках тех же данных попробуйте предсказать `price_category` с помощью алгоритма логистической регрессии. Предварительно из датафрейма удалите переменные, в которых косвенно содержится информация о целевой переменной (`odometer/price_std`, `price`). 

Для обученной модели нужно:

- рассчитать и вывести метрику качества (accuracy) на тренировочной выборке;
- сделать предикт на тестовых данных и положить его в переменную `logreg_pred`;
- рассчитать и вывести accuracy и confusion_matrix на тестовой выборке.


Задание засчитывается, если: 
- accuracy на тренировочной выборке > 87%;
- accuracy на тестовой выборке > 75.5%.

Для улучшения метрики можно преобразовывать входные данные, тюнить параметры логистической регрессии.

In [19]:
from sklearn.preprocessing import StandardScaler
df_prepared = df.drop(columns=['odometer/price_std', 'price_category', 'id'])
X = df.drop(columns=['price_category'])
y = df['price_category']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


logreg_model = LogisticRegression(random_state=42, solver='liblinear', penalty='l1', C=0.5)  
logreg_model.fit(X_train, y_train)

train_pred = logreg_model.predict(X_train)
train_accuracy = accuracy_score(y_train, train_pred)
print(f'Accuracy на тренировочной выборке: {train_accuracy}')


logreg_pred = logreg_model.predict(X_test)


test_accuracy = accuracy_score(y_test, logreg_pred)
print(f'Accuracy на тестовой выборке: {test_accuracy}')

conf_matrix = confusion_matrix(y_test, logreg_pred)
print(f'Confusion Matrix:\n{conf_matrix}')
#Добавил удаление 'id'

Accuracy на тренировочной выборке: 0.9936135452250111
Accuracy на тестовой выборке: 0.9674289674289674
Confusion Matrix:
[[979   0  18]
 [  0 925  28]
 [ 20  28 888]]


**Задача 2. Многослойный персептрон**

Решите задачу, поставленную в предыдущем задании, применив модель многослойного персептрона. Добейтесь лучших значений точности на тренировочной и тестовой выборках, чем на логистической регрессии, с помощью данного алгоритма. 

Значимым увеличением точности в данном задании будем считать увеличение больше, чем на 0.01 по метрике accuracy.

In [118]:
df_prepared = df
X = df_prepared.drop(columns=['price_category'])
y = df_prepared['price_category']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


mlp_model = MLPClassifier(hidden_layer_sizes=(256, 128, 64),  
                            activation='relu',      
                            solver='adam',           
                            alpha=0.0001,         
                            batch_size='auto',
                            learning_rate='adaptive',
                            max_iter=300,           
                            random_state=42)         
mlp_model.fit(X_train, y_train)

train_pred = mlp_model.predict(X_train)
train_accuracy = accuracy_score(y_train, train_pred)
print(f'Accuracy на тренировочной выборке: {train_accuracy}')

mlp_pred = mlp_model.predict(X_test)

test_accuracy = accuracy_score(y_test, mlp_pred)
print(f'Accuracy на тестовой выборке: {test_accuracy}')

conf_matrix = confusion_matrix(y_test, mlp_pred)
print(f'Confusion Matrix:\n{conf_matrix}')

Accuracy на тренировочной выборке: 0.9961384226941927
Accuracy на тестовой выборке: 0.8416493416493417
Confusion Matrix:
[[836   5 156]
 [  2 848 103]
 [ 61 130 745]]


**Задача 3. Сравнение с древовидными моделями**

Обучите модель случайного леса на тех же данных для предсказания `price_category`. Сравните качество с моделью логистической регрессии и многослойного персептрона. Словами опишите, какая из моделей в каких случаях работает лучше по результатам на тестовой выборке, и обоснуйте свой выбор.

In [124]:
from sklearn.ensemble import RandomForestClassifier

X = df_prepared.drop(columns=['price_category'])
y = df_prepared['price_category']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

rf_model = RandomForestClassifier(n_estimators=100, random_state=42) 
rf_model.fit(X_train, y_train)  
rf_pred = rf_model.predict(X_test)
rf_accuracy = accuracy_score(y_test, rf_pred)
print(f'Random Forest Accuracy: {rf_accuracy}')
#Н у пока что случайный лес работает лучше всех на тестовой выборке, ну по самому простой метрике - аккураси(просто я ещё узнал про рекол и пресижен) 

Random Forest Accuracy: 0.9809424809424809


**Задача 4. Стратегия голосования**

Реализуйте стратегию голосования для предсказания целевой переменной.
Голосование в задаче классификации — это когда несколько моделей выдают свои предикты, и финальным выбирается тот предикт, который предсказали большинство моделей.

Для реализации этой стратегии проделайте следующее:

- сохраните предсказания каждой из моделей (случайный лес, многослойный персептрон, логистическая регрессия) для тестовой выборки в датафрейм `pred_df`;
- в четвертую колонку `target` положите тот класс, который предсказало большинство классификаторов. Например, если в строке были значения `high, medium, medium`, в `target` нужно положить `medium`.

     Если в строке три разных класса — `high, medium, low`, — придумайте свою стратегию по выбору значения. Самая простая стратегия: выбрать рандомно одно значение из трёх.

- посчитайте точность предсказания с помощью голосования. Выведите значения метрик accuracy и confusion_matrix.


Добейтесь значения точности > 78% 

In [128]:
import random
df_prepared = df.drop(columns=['odometer/price_std', 'price', 'id'])

X = df_prepared.drop(columns=['price_category'])
y = df_prepared['price_category']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

logreg_model = LogisticRegression(random_state=42, solver='liblinear', penalty='l1', C=0.5)
logreg_model.fit(X_train_scaled, y_train)
logreg_pred = logreg_model.predict(X_test_scaled)


mlp_model = MLPClassifier(hidden_layer_sizes=(256, 128, 64), activation='relu', solver='adam',
                           alpha=0.0001, max_iter=300, random_state=42)
mlp_model.fit(X_train_scaled, y_train)
mlp_pred = mlp_model.predict(X_test_scaled)


rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)


pred_df = pd.DataFrame({
    'logreg': logreg_pred,
    'mlp': mlp_pred,
    'rf': rf_pred
})


def voting_strategy(row):

    counts = row.value_counts()
    if len(counts) == 3:
        return random.choice(row.tolist())
    else:
        return counts.index[0]

pred_df['target'] = pred_df.apply(voting_strategy, axis=1)


voting_accuracy = accuracy_score(y_test, pred_df['target'])
conf_matrix_voting = confusion_matrix(y_test, pred_df['target'])

print(f'Voting Accuracy: {voting_accuracy}')
print(f'Confusion Matrix (Voting):\n{conf_matrix_voting}')


Voting Accuracy: 0.7688842688842689
Confusion Matrix (Voting):
[[834  30 133]
 [ 19 793 141]
 [170 174 592]]


**Примечание:**

В этом домашнем задании в задаче номер 1 и далее перед вами встал выбор: включать ли в обучение колонку `id`. При удалении данной колонки во время обучении логистической регрессии качество заметно улучшается.

Вообще обучать любую модель (будь то логистическая или линейная регрессия, или древовидный алгоритм) на данных айдишников не считается хорошей практикой. Как правило, между `id` и целевой переменной не должно быть никаких взаимосвязей. Включая колонку `id` в качества атрибута в обучение, вы стараетесь "заточить" результаты своей модели под айдишники записей. Таким образом модель обучится на некотором наборе "частных случаев", и, возможно, не обратит внимание на общие зависимости.   